site_name: How to
site_url: https://how-to.fun
site_author: Julyfun
site_description: >-
  How to reproduce and solve a problem, tested very useful.
repo_name: how-to
repo_url: https://github.com/julyfun/how-to

theme:
  name: material
  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto Slab
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/julyfun/how-to
  analytics:
    provider: google
    property: G-09J8ZCVSWW

plugins:
  - search:
      lang:
        - zh
        - en
      # very useful. ref: https://squidfunk.github.io/mkdocs-material/blog/2022/05/05/chinese-search-support/?h=%E6%9B%B4
      separator: '[\s\u200b\-]' 
  - minify:
      minify_html: true
